name: Deploy para Vercel com verificação de HTML

on:
  push:
    branches:
      - main  # O deploy será feito quando houver um push na branch "main"
  pull_request:
    branches:
      - main  # Roda quando há um pull request para a branch "main"

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Verificar se o HTML está presente
      run: |
        # Verifica se existe um arquivo .html na raiz ou em uma pasta específica
        if ! find . -type f -name "*.html" -exec false; then
          echo "Nenhum arquivo HTML encontrado. O deploy será interrompido."
          exit 1
        else
          echo "Arquivo HTML encontrado. Prosseguindo com o deploy."
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-html  # O deploy só será executado após a verificação de HTML ser bem-sucedida

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar o Vercel CLI
      run: |
        npm install -g vercel

    - name: Fazer login no Vercel
      run: |
        vercel login ${{ secrets.VERCEL_TOKEN }}  # Usando um token de autenticação seguro (adicione no GitHub Secrets)

    - name: Deploy no Vercel
      run: |
        vercel --prod --confirm  # O deploy será feito para o ambiente de produção

